name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: |
          corepack enable
          pnpm --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base libcurl4-openssl-dev libxml2-dev libxslt1-dev pkg-config

      - name: Install tooling
        run: pip install pre-commit ruff

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Lint
        run: make lint

      - name: Run go-test with coverage guard
        run: |
          make go-test
          cat coverage.summary
          rm -f coverage.summary
