name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: |
          corepack enable
          pnpm --version

      - name: Cache tooling artifacts
        uses: actions/cache@v4
        with:
          path: .cache
          key: cache-dotcache-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml', 'pyproject.toml', 'Makefile', 'scripts/run_lintr.py') }}
          restore-keys: |
            cache-dotcache-${{ runner.os }}-

      - name: Install APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: r-base libcurl4-openssl-dev libxml2-dev libxslt1-dev pkg-config
          version: 1

      - name: Install tooling
        run: pip install pre-commit ruff

      - name: Run pre-commit
        run: |
          PRE_COMMIT_HOME=$PWD/.cache/pre-commit \
          XDG_CACHE_HOME=$PWD/.cache \
          pre-commit run --all-files
