name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_VERSION: v2.4.0
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Lint
        run: make lint

      - name: Run go-test with coverage guard
        run: |
          make go-test
          cat coverage.summary
          rm -f coverage.summary
