name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_VERSION: v1.60.3
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_VERSION}
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Lint
        run: make lint

      - name: Run go-test with coverage guard
        run: |
          make go-test
          cat coverage.summary
          rm -f coverage.summary
